### ISSUE TITLE
No transparency around "Link confirmation" pop-up when using Catppuccin Mocha theme

### ISSUE THREAD

**Issue by Occhioverde** [catppuccin/proton#2]
Good morning.
As the issue title says, today I noticed that there is no transparency around the "Link confirmation" pop-up when using the Catppuccin Mocha theme:

![Pop-up with Catppuccin Mocha enabled](https://user-images.githubusercontent.com/18429412/218318943-1b025bb9-301b-4cf4-ba5e-aaa219b872e3.png)

For reference, here is the same view when Catppuccin Mocha is disabled:

![Pop-up with Catppuccin Mocha disabled](https://user-images.githubusercontent.com/18429412/218319103-2034166a-12f9-41aa-98c9-6a91de71c30b.png)

**Comment by soya-daizu** [comment]
Fixed in 9109d04.
